### ISSUE TITLE
Error while adding it.

### ISSUE THREAD

**Issue by HelloLudger** [smeevil/responsive-block-grid#3]
```
> meteor add smeevil:reactive-block-grid
 => Errors while adding packages:

While checking for fourseven:scss@1.0.0:
error: No compatible build found
```

I use the newest preview for Windows (0.3.0)

**Comment by dcsan** [comment]
apparently that dependency isn't needed anymore. you can wait for @smeevil to merge a PR i sent or check out my fork 
https://github.com/dcsan/responsive-block-grid
