### ISSUE TITLE
upgrade scss

### ISSUE THREAD

**Issue by dcsan** [smeevil/responsive-block-grid#4]
the problematic fourseven plugin is causing hassle as usual (it's the bane of meteoric project too)

   While selecting package versions:
   error: Conflict: Constraint fourseven:scss@1.0.0 is not satisfied by fourseven:scss 2.0.1_5.
   Constraints on package "fourseven:scss":
- fourseven:scss@2.0.0 <- meteoric:ionicons-sass 0.1.6
- fourseven:scss@2.0.0 <- meteoric:ionic-sass 0.1.9
- fourseven:scss@1.0.0 <- smeevil:reactive-block-grid 1.0.1 <- chatu:chapters 0.0.2

**Comment by smeevil** [comment]
I default to sass and is part of my skeleton, in this case it was quite overkill :) I dropped the dep and made it plain css.

Let me know how this works out for you :)

**Comment by dcsan** [comment]
oh i just forked and fixed. i guess i'll just remove the dep? yep, that works!
